services:
  driver:
    image: led-clock-backend-driver:local
    build: 
      context: ../../
      dockerfile: driver.dockerfile
    ports: 
      - "8888:8888"
      - "7777:7777"
    restart: always
    networks:
      bridge:
        aliases:
          - driver
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
    environment:
      - LOCAL_DEV=true
    # # Run privileged mode to access the GPIO pins (not needed for local dev)
    # privileged: true
  server:
    image: led-clock-backend-server:local
    build: 
      context: ../../
      dockerfile: server.dockerfile
    ports: 
      - "8000:8000"
    restart: always
    networks:
      bridge:
        aliases:
          - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback

networks:
  bridge:
    name: led-clock-network
    driver: bridge