name: led-clock-backend

services:
  init:
    image: busybox
    command: ["sh", "-c", "chmod -R 777 /app/saved-matrices"]
    volumes:
      - led-clock-data:/app/saved-matrices
    networks:
      - bridge

  driver:
    image: ghcr.io/danielatanasovski/led-clock-backend-driver:latest
    container_name: led-driver
    hostname: led-driver
    ports: 
      - "8888:8888"
    restart: always
    user: root
    networks:
      bridge:
        aliases:
          - driver
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
    # Run privileged mode to access the GPIO pins
    privileged: true
    volumes:
      - type: volume
        source: led-clock-data
        target: /app/saved-matrices

  server:
    image: ghcr.io/danielatanasovski/led-clock-backend-server:latest
    container_name: led-backend
    hostname: led-backend
    environment:
      - DRIVER_URL=led-driver
    ports: 
      - "8000:8000"
    restart: always
    networks:
      bridge:
        aliases:
          - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      update_config:
        parallelism: 2
        delay: 10s
        failure_action: rollback
    volumes:
      - type: volume
        source: led-clock-data
        target: /app/saved-matrices

volumes:
  led-clock-data:

networks:
  bridge:
    name: led-clock-network
    driver: bridge