name: Deploy Driver and Server to Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "aurora"
        type: string
      version:
        description: "Version to deploy"
        required: true
        default: "latest"
        type: string

env:
  STACK_NAME: "led-backend"

jobs:
  deploy:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Connect to Tailscale network
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # Setup Docker remote Context
      - uses: alex-ac/github-action-ssh-docker-compose@master
        name: Docker-Compose Remote Deployment
        with:
          ssh_host: ${{ secrets.LED_PI_ADDRESS }}
          ssh_private_key: ${{ secrets.LED_PI_SSH_KEY }}
          ssh_user: ${{ secrets.LED_PI_USER }}
          docker_compose_prefix: led-clock-backend
          docker_compose_filename: .github/deploy/docker-compose.aurora.yml
